variables:
  APP_ORIGINAL_NAME: demo-0.0.1-SNAPSHOT.jar
  APP_NAME: demo-0.0.1-SNAPSHOT-v$CI_PIPELINE_IID.jar
  APP_SIMPLE_NAME: demo
  ENV_NAME: demo-env

stages:
  # - test_env_variables
  - build
  # - test
  - deploy

# show env variables:
#   stage: test_env_variables
#   script: 
#     - echo "ID" $CI_PIPELINE_ID
#     - echo "IID" $CI_PIPELINE_IID

build:
  stage: build
  image: openjdk:17-bullseye
  script:
    - chmod +x gradlew
    - ./gradlew build
    - mv ./build/libs/$APP_ORIGINAL_NAME ./build/libs/$APP_NAME
  artifacts:
    paths:
    # Permite que tal caminho seja preservado para uso de outros jobs
      - ./build/libs/

# test:
#   stage: test
#   image: openjdk:17-bullseye
#   script:
#     - java -jar ./build/libs/$APP_NAME & 
#     - sleep 20
#     - curl http://localhost:8080/ping | grep "pong"

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws configure set region us-east-1
    - aws s3 cp ./build/libs/$APP_NAME s3://$S3_BUCKET/$APP_NAME
    - aws elasticbeanstalk create-application-version --application-name $APP_SIMPLE_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$S3_BUCKET,S3Key=$APP_NAME
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name=$ENV_NAME --version-label $CI_PIPELINE_IID